version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "xarlizard"
    assignees:
      - "xarlizard"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "xarlizard"
    assignees:
      - "xarlizard"
    commit-message:
      prefix: "ci"
      include: "scope"
