name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.npmjs.com/package/@xarlizard/react-temporal

    steps:
      - uses: actions/checkout@v5

      - name: Build and Deploy
        run: echo "This is a template. Add your deployment command here, e.g., npm run deploy, scp, rsync, or a cloud CLI."
